### PR TITLE
version 0.2.5

### PR DESCRIPTION
**Pull request by FabianHofmann**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FabianHofmann** [comment]
@conda-forge-admin, please rerender

**Review by coroa — APPROVED** [review]
LGTM.

But didn't check whether there were any dependency updates between the versions.

**Comment by coroa** [comment]
Strange that the bot didn't trigger.

**Comment by FabianHofmann** [comment]
> Strange that the bot didn't trigger.

As far as I see it's because the tar.gz was not uploaded (https://github.com/PyPSA/atlite/runs/2904716834#step:4:93). However it's still strange that it wasn't built in the first place

**Pull request merged**
